package dss.pqt.travelExp.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 29 14:07:17 PKT 2016
// ---------------------------------------------------------------------
public interface DssTravelExpanseReimbursementView extends ViewObject {
    void setNVC_WfDocumentId(oracle.jbo.domain.Number value);

    void travelExpSearchUser();
}

