package dss.pqt.travelExp.model.vo;

import dss.pqt.travelExp.model.eo.DssTravelexpanseDetailImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 23 11:25:26 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DssTravelexpanseDetailViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_DSSTRAVELEXPANSEDETAIL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DetailDate,
        EnterDate,
        ExpIdFk,
        FareAmount,
        FromLocation,
        LastUpdatedBy,
        LastUpdatedDate,
        OtherAmount,
        RoutIdPk,
        TaxAmount,
        ToLocation,
        TotAmount,
        TransportMode,
        Transportation,
        TripType,
        UserIdFk,
        VoucherIdFk,
        TotSumAmount,
        DssTravelexpanseSetupLOV1,
        trpTypeLOV1,
        DssTravelexpanseRoutsetupLOV1,
        DssTravelexpanseSetupLOV2,
        DssTravelexpanseRoutsetupLOV2;
        static AttributesEnum[] vals = null; ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DETAILDATE = AttributesEnum.DetailDate.index();
    public static final int ENTERDATE = AttributesEnum.EnterDate.index();
    public static final int EXPIDFK = AttributesEnum.ExpIdFk.index();
    public static final int FAREAMOUNT = AttributesEnum.FareAmount.index();
    public static final int FROMLOCATION = AttributesEnum.FromLocation.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int OTHERAMOUNT = AttributesEnum.OtherAmount.index();
    public static final int ROUTIDPK = AttributesEnum.RoutIdPk.index();
    public static final int TAXAMOUNT = AttributesEnum.TaxAmount.index();
    public static final int TOLOCATION = AttributesEnum.ToLocation.index();
    public static final int TOTAMOUNT = AttributesEnum.TotAmount.index();
    public static final int TRANSPORTMODE = AttributesEnum.TransportMode.index();
    public static final int TRANSPORTATION = AttributesEnum.Transportation.index();
    public static final int TRIPTYPE = AttributesEnum.TripType.index();
    public static final int USERIDFK = AttributesEnum.UserIdFk.index();
    public static final int VOUCHERIDFK = AttributesEnum.VoucherIdFk.index();
    public static final int TOTSUMAMOUNT = AttributesEnum.TotSumAmount.index();
    public static final int DSSTRAVELEXPANSESETUPLOV1 = AttributesEnum.DssTravelexpanseSetupLOV1.index();
    public static final int TRPTYPELOV1 = AttributesEnum.trpTypeLOV1.index();
    public static final int DSSTRAVELEXPANSEROUTSETUPLOV1 = AttributesEnum.DssTravelexpanseRoutsetupLOV1.index();
    public static final int DSSTRAVELEXPANSESETUPLOV2 = AttributesEnum.DssTravelexpanseSetupLOV2.index();
    public static final int DSSTRAVELEXPANSEROUTSETUPLOV2 = AttributesEnum.DssTravelexpanseRoutsetupLOV2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DssTravelexpanseDetailViewRowImpl() {
    }

    /**
     * Gets DssTravelexpanseDetail entity object.
     * @return the DssTravelexpanseDetail
     */
    public DssTravelexpanseDetailImpl getDssTravelexpanseDetail() {
        return (DssTravelexpanseDetailImpl) getEntity(ENTITY_DSSTRAVELEXPANSEDETAIL);
    }

    /**
     * Gets the attribute value for DETAIL_DATE using the alias name DetailDate.
     * @return the DETAIL_DATE
     */
    public Date getDetailDate() {
        return (Date) getAttributeInternal(DETAILDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL_DATE using the alias name DetailDate.
     * @param value value to set the DETAIL_DATE
     */
    public void setDetailDate(Date value) {
        setAttributeInternal(DETAILDATE, value);
    }

    /**
     * Gets the attribute value for ENTER_DATE using the alias name EnterDate.
     * @return the ENTER_DATE
     */
    public Date getEnterDate() {
        return (Date) getAttributeInternal(ENTERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTER_DATE using the alias name EnterDate.
     * @param value value to set the ENTER_DATE
     */
    public void setEnterDate(Date value) {
        setAttributeInternal(ENTERDATE, value);
    }

    /**
     * Gets the attribute value for EXP_ID_FK using the alias name ExpIdFk.
     * @return the EXP_ID_FK
     */
    public Number getExpIdFk() {
        return (Number) getAttributeInternal(EXPIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for EXP_ID_FK using the alias name ExpIdFk.
     * @param value value to set the EXP_ID_FK
     */
    public void setExpIdFk(Number value) {
        setAttributeInternal(EXPIDFK, value);
    }

    /**
     * Gets the attribute value for FARE_AMOUNT using the alias name FareAmount.
     * @return the FARE_AMOUNT
     */
    public Number getFareAmount() {
        return (Number) getAttributeInternal(FAREAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for FARE_AMOUNT using the alias name FareAmount.
     * @param value value to set the FARE_AMOUNT
     */
    public void setFareAmount(Number value) {
        setAttributeInternal(FAREAMOUNT, value);
        int a = 0;
        int b = 0;
        int c = 0;
        try {
            a = getTaxAmount().intValue();
        } catch (Exception e) {
            a = 0;
        }
        try {
            b = getFareAmount().intValue();
        } catch (Exception e) {
            b = 0;
        }
        try {
            c = getOtherAmount().intValue();
        } catch (Exception e) {
            c = 0;
        }

        int d = a + b + c;

        setTotAmount(new Number(d));

    }

    /**
     * Gets the attribute value for FROM_LOCATION using the alias name FromLocation.
     * @return the FROM_LOCATION
     */
    public String getFromLocation() {
        return (String) getAttributeInternal(FROMLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for FROM_LOCATION using the alias name FromLocation.
     * @param value value to set the FROM_LOCATION
     */
    public void setFromLocation(String value) {
        setAttributeInternal(FROMLOCATION, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for OTHER_AMOUNT using the alias name OtherAmount.
     * @return the OTHER_AMOUNT
     */
    public Number getOtherAmount() {
        return (Number) getAttributeInternal(OTHERAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_AMOUNT using the alias name OtherAmount.
     * @param value value to set the OTHER_AMOUNT
     */
    public void setOtherAmount(Number value) {
        setAttributeInternal(OTHERAMOUNT, value);
        int a = 0;
        int b = 0;
        int c = 0;
        try {
            a = getTaxAmount().intValue();
        } catch (Exception e) {
            a = 0;
        }
        try {
            b = getFareAmount().intValue();
        } catch (Exception e) {
            b = 0;
        }
        try {
            c = getOtherAmount().intValue();
        } catch (Exception e) {
            c = 0;
        }
        int d = a + b + c;

        setTotAmount(new Number(d));
    }

    /**
     * Gets the attribute value for ROUT_ID_PK using the alias name RoutIdPk.
     * @return the ROUT_ID_PK
     */
    public Number getRoutIdPk() {
        return (Number) getAttributeInternal(ROUTIDPK);
    }

    /**
     * Sets <code>value</code> as attribute value for ROUT_ID_PK using the alias name RoutIdPk.
     * @param value value to set the ROUT_ID_PK
     */
    public void setRoutIdPk(Number value) {
        setAttributeInternal(ROUTIDPK, value);
    }

    /**
     * Gets the attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @return the TAX_AMOUNT
     */
    public Number getTaxAmount() {
        return (Number) getAttributeInternal(TAXAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TAX_AMOUNT using the alias name TaxAmount.
     * @param value value to set the TAX_AMOUNT
     */
    public void setTaxAmount(Number value) {
        setAttributeInternal(TAXAMOUNT, value);
        int a = 0;
        int b = 0;
        int c = 0;
        try {
            a = getTaxAmount().intValue();
        } catch (Exception e) {
            a = 0;
        }
        try {
            b = getFareAmount().intValue();
        } catch (Exception e) {
            b = 0;
        }
        try {
            c = getOtherAmount().intValue();
        } catch (Exception e) {
            c = 0;
        }
        int d = a + b + c;

        setTotAmount(new Number(d));
    }

    /**
     * Gets the attribute value for TO_LOCATION using the alias name ToLocation.
     * @return the TO_LOCATION
     */
    public String getToLocation() {
        return (String) getAttributeInternal(TOLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for TO_LOCATION using the alias name ToLocation.
     * @param value value to set the TO_LOCATION
     */
    public void setToLocation(String value) {
        setAttributeInternal(TOLOCATION, value);
    }

    /**
     * Gets the attribute value for TOT_AMOUNT using the alias name TotAmount.
     * @return the TOT_AMOUNT
     */
    public Number getTotAmount() {
        return (Number) getAttributeInternal(TOTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_AMOUNT using the alias name TotAmount.
     * @param value value to set the TOT_AMOUNT
     */
    public void setTotAmount(Number value) {
        setAttributeInternal(TOTAMOUNT, value);
    }

    /**
     * Gets the attribute value for TRANSPORT_MODE using the alias name TransportMode.
     * @return the TRANSPORT_MODE
     */
    public String getTransportMode() {
        return (String) getAttributeInternal(TRANSPORTMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSPORT_MODE using the alias name TransportMode.
     * @param value value to set the TRANSPORT_MODE
     */
    public void setTransportMode(String value) {
        setAttributeInternal(TRANSPORTMODE, value);
    }

    /**
     * Gets the attribute value for TRANSPORTATION using the alias name Transportation.
     * @return the TRANSPORTATION
     */
    public String getTransportation() {
        return (String) getAttributeInternal(TRANSPORTATION);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSPORTATION using the alias name Transportation.
     * @param value value to set the TRANSPORTATION
     */
    public void setTransportation(String value) {
        setAttributeInternal(TRANSPORTATION, value);
    }

    /**
     * Gets the attribute value for TRIP_TYPE using the alias name TripType.
     * @return the TRIP_TYPE
     */
    public String getTripType() {
        return (String) getAttributeInternal(TRIPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIP_TYPE using the alias name TripType.
     * @param value value to set the TRIP_TYPE
     */
    public void setTripType(String value) {
        setAttributeInternal(TRIPTYPE, value);
    }

    /**
     * Gets the attribute value for USER_ID_FK using the alias name UserIdFk.
     * @return the USER_ID_FK
     */
    public Number getUserIdFk() {
        return (Number) getAttributeInternal(USERIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID_FK using the alias name UserIdFk.
     * @param value value to set the USER_ID_FK
     */
    public void setUserIdFk(Number value) {
        setAttributeInternal(USERIDFK, value);
    }

    /**
     * Gets the attribute value for VOUCHER_ID_FK using the alias name VoucherIdFk.
     * @return the VOUCHER_ID_FK
     */
    public Number getVoucherIdFk() {
        return (Number) getAttributeInternal(VOUCHERIDFK);
    }

    /**
     * Sets <code>value</code> as attribute value for VOUCHER_ID_FK using the alias name VoucherIdFk.
     * @param value value to set the VOUCHER_ID_FK
     */
    public void setVoucherIdFk(Number value) {
        setAttributeInternal(VOUCHERIDFK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotSumAmount.
     * @return the TotSumAmount
     */
    public Number getTotSumAmount() {
        return (Number) getAttributeInternal(TOTSUMAMOUNT);
    }


    /**
     * Gets the view accessor <code>RowSet</code> DssTravelexpanseSetupLOV1.
     */
    public RowSet getDssTravelexpanseSetupLOV1() {
        return (RowSet) getAttributeInternal(DSSTRAVELEXPANSESETUPLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> trpTypeLOV1.
     */
    public RowSet gettrpTypeLOV1() {
        return (RowSet) getAttributeInternal(TRPTYPELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DssTravelexpanseRoutsetupLOV1.
     */
    public RowSet getDssTravelexpanseRoutsetupLOV1() {
        return (RowSet) getAttributeInternal(DSSTRAVELEXPANSEROUTSETUPLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DssTravelexpanseSetupLOV2.
     */
    public RowSet getDssTravelexpanseSetupLOV2() {
        return (RowSet) getAttributeInternal(DSSTRAVELEXPANSESETUPLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DssTravelexpanseRoutsetupLOV2.
     */
    public RowSet getDssTravelexpanseRoutsetupLOV2() {
        return (RowSet) getAttributeInternal(DSSTRAVELEXPANSEROUTSETUPLOV2);
    }
}

